### PR TITLE
codemirror binding

### PR DESCRIPTION
**Pull request by druuu**
@dmonad 
probably the code standards suck, let me know.
willing to help.

### CODE REVIEW

**Comment by dmonad** [comment]
Hey @druuu - you still up for this?

**Comment by druuu** [comment]
@dmonad yes.

**Comment by dmonad** [comment]
Sorry for ignoring this PR for so long. It looks really good. I have changed the codebase quite a bit since then, but I'd be happy to include this PR.

Would you be willing to refactor this? 

In order to merge this, I need the codemirror example working again. You can copy the textarea example to get started. 

There is a basic websockets server included in the master branch. Use it to let several clients connect to the codemirror example. `node ./provider/websocket/server.js`.

Let me know if you have any questions or get stuck

- Kevin

**Comment by druuu** [comment]
Glad to hear that.
I will setup the example and refactor the code.

Thanks for the awesome library.

**Comment by dmonad** [comment]
Thanks @druuu appreciating your help :)

**Comment by dmonad** [comment]
Hi @druuu 
I implemented a codemirror binding with cursor support. You can check it out here https://yjs.website/tutorial-codemirror.html#

**Pull request closed without merging**
